shopshow/shop/urls.py
from django.urls import path
from .import views

app_name = 'shop'
urlpatterns = [
    path('', views.ProductsView.as_view(), name='product_list'),
    path('<str:category_slug>/', views.ProductsView.as_view(), name='product_list_by_category'),
    path('<int:id>/<str:slug>/', views.ProductDetailView.as_view(), name='product_detail')
]

shopshow/shopshow/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shopshow/shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)

    verbose_name = 'category'
    verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE,
                                 related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

shopshow/shop/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import View

from .models import Product, Category


class ProductsView(View):
    def get(self, request, category_slug=None):
        category = None

        categories = Category.objects.all()
        products = Product.objects.filter(available=True)

        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            products = products.filter(category=category)
        return render(request, 'shop/product/list.html', {'category': category,
                                                          'categories': categories,
                                                          'products': products})


class ProductDetailView(View):
    def get(self, request, id, slug):
        product = get_object_or_404(Product, id=id, slug=slug, available=True)
        return render(request, 'shop/product/detail.html', {'product': product})


shopshow/shop/templates/shop/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "bootstrap-4.1.1/dist/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "font-awesome-4.7.0/css/font-awesome.min.css" %}">
    <link rel="stylesheet" href="{% static "bootstrap-social-gh-pages/bootstrap-social.css" %}">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    {% block custom_css %}{% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}

<script src="{% static "js/jquery-3.3.1.min.js" %}"></script>
<script src="{% static "js/popper.min.js" %}"></script>
<script src="{% static "bootstrap-4.1.1/dist/js/bootstrap.min.js" %}"></script>
</body>
</html>

shopshow/shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block custom_css %}e
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block title %}
    {% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
    <nav class="navbar navbar-expand-sm navbar-dark bg-primary ">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#Navbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="/">Shop show</a>
            <div class="collapse navbar-collapse" id="Navbar">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'shop:product_list' %}">
                            <span class="fa fa-home fa-lg"></span>
                            Home
                        </a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
    <header class="jumbotron" style="padding: 0;">
        <div class="container">
            <div class="row justify-content-end">
                <div>
                    <p style="margin: 10px">Your cart is empty!</p>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-4 " " >
                <img src="{{ product.image.url }}" width="100%">
            </div>
            <div class="col-12 col-sm-8">
                <h1>{{ product.name }}</h1>
                <h2>
                    <a href="{{ product.category.get_absolute_url }}">
                        {{ product.category }}
                    </a>
                </h2>
                <p class="price">${{ product.price }}</p>
{#                <form action="{% url 'cart:cart_add' product.id %}" method="post">#}
{#                    {{ cart_product_form }}#}
{#                    {% csrf_token %}#}
{#                    <input class="btn btn-primary btn-sm" type="submit" value="Add to cart">#}
{#                </form>#}
                {{ product.description|linebreaks }}
            </div>
        </div>


    </div>
{% endblock %}

shopshow/shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block custom_css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
    <nav class="navbar navbar-expand-sm navbar-dark bg-primary ">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#Navbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="/">Shop show</a>
            <div class="collapse navbar-collapse" id="Navbar">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">
                            <span class="fa fa-home fa-lg"></span>
                            Home
                        </a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
    <header class="jumbotron" style="padding: 0;">
        <div class="container">
            <div class="row justify-content-end">
                <div>
                    <p style="margin: 10px">Your cart is empty!</p>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <div class="row row-content ">
            <div class="col-12 col-sm-2 ">
                <h3>Categories</h3>
                <ul id="sidermenu" class="nav flex-column">
                  <li {% if not category %}class="nav-item active"{% else %}class="nav-item"{% endif %}>
                    <a class="nav-link " href="{% url 'shop:product_list' %}">All</a>
                  </li>
                {% for c in categories %}
                  <li {% if category.slug == c.slug %}class="nav-item active"{% else %}class="nav-item"{% endif %}>
                    <a class="nav-link" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                  </li>
                {% endfor %}
                </ul>
            </div>
            <div class="col-12 col-sm ">
                <h2>{% if category %}{{ category.name }}{% else %}全部商品{% endif %}</h2>
                <div class="row">
                    {% for product in products %}
                        <div class="col-12 col-sm-3">
                            <div class="item" style="text-align:center;">
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{{ product.image.url }} " style='width:100%'>
                                </a>
                                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
                                ${{ product.price }}
                            </div>

                        </div>
                    {% endfor %}

                </div>
            </div>
        </div>
#分页功能区
    </div>
{% endblock %}